### ISSUE TITLE
Python 3 error in _sendDDEcommand in error is returned from any Request

### ISSUE THREAD

**Issue by magro11** [indranilsinharoy/PyZDDE#49]
Hello together,
when communicating with Zemax, the method _sendDDEcommand is often called. Usually the answer variable reply contains a byte object (Python 3). However, if an error occurs (e.g. timeout), a string (str) is contained in reply (e.g. '-998'). Then the decode command

```
reply = reply.decode('ascii').rstrip()
```

fails.

A solution might be to use the following version of the function:

```
def _sendDDEcommand(self, cmd, timeout=None):
        """Method to send command to DDE client
        """
        global _global_pyver3
        reply = self._conversation.Request(cmd, timeout)
        if _global_pyver3:
            if type(reply) is bytes:
                reply = reply.decode('ascii').rstrip()
            else:
                reply = reply.rstrip()
        return reply
```

However, it might also be, that it is not desired that any string is returned by _conversation.Request.

Cheers
Marc

**Comment by indranilsinharoy** [comment]
Hi Marc,

Do you have a traceback of the error message? I somehow like your second suggestion that perhaps ``_conversation.Request`` should send ``b'-998'`` (Python 3 byte) instead of ``'-998'`` (Python 3 string) when the environment is Python 3. 

One way to do it would be (there might be a better solution) the following modifications in ``ddeclient.py``:

* Create a global variable ``_global_timeout_code``
* Assign:   ``_global_timeout_code = b'-998' if _global_pyver3 else '-998'``
* Replace the line ``reply = '-998'`` to ``reply =  _global_timeout_code`` in the class method ``CreateConversation.Request()``

Note that the variable ``_global_pyver3`` is currently not there in the module ``ddeclient.py``. We can either import it from ``config.py`` or detect Python version in ``ddeclient.py``. 

What do you think?

**Comment by magro11** [comment]
Hi,
unfortunately, I did not save the traceback. However, I also think that the error comes from the Request method in ddeclient.py. 

I think I would avoid the usage of too much global variables. Why not using the following implementation:

```
def Request(self, item, timeout=None):
    """Request DDE client
    timeout in seconds
    Note ... handle the exception within this function.
    """
    if not timeout:
        timeout = self.ddetimeout
    try:
        reply = self.ddec.request(item, int(timeout*1000)) # convert timeout into milliseconds
    except DDEError:
        err_str = str(sys.exc_info()[1])
        error = err_str[err_str.find('err=')+4:err_str.find('err=')+10]
        if error == hex(DMLERR_DATAACKTIMEOUT):
            print("TIMEOUT REACHED. Please use a higher timeout.\n")
        if (sys.version_info > (3, 0)): #this is only evaluated in case of an error
            reply = b'-998' #Timeout error value
        else:
            reply = '-998' #Timeout error value
    return reply
```

sys is already imported, sys.version_info is a constant and therefore does not need time to be evaluated. Anyways, the timeout values are only assigned in case of an error, such that the default case runs without overhead.

Cheers
Marc

**Comment by indranilsinharoy** [comment]
Hi Marc,

I like the solution. Can you send a PR?

**Comment by indranilsinharoy** [comment]
Thanks, Marc.
